apiVersion: v1
kind: Service
metadata:
  name: ecr-demoapp-nodeport-svc
  labels:
    app: ecr-demoapp
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /index.html
spec:
  type: NodePort
  selector:
    app: ecr-demoapp
  ports:
    - port: 80
      targetPort: 80
