apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote-app-node-port-svc
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - name: "vote-service"
      port: 80
      targetPort: 80
