---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: labekscluster
  region: us-east-1

managedNodeGroups:
  name: eks-public-nodegroup
  instanceType: t3.small
  minSize: 1
  maxSize: 3
  desiredCapacity: 2
  volumeSize: 20
  ssh:
    allow: true
    publicKey: binWinWebServerKey
  withAddonPolicies:
    autoScaler: true
    externalDNS: true
    imageBuilder: true
    albIngress: true
    appMesh: true
