apiVersion: v1
kind: Pod
metadata:
  name: bin-configmap
spec:
  containers:
    - name: bin-container
      image: busybox
      command: ["sh", "-c", "echo $(MY_VAR) && sleep 3600"]
      env:
        - name: MY_VAR
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: db_name
