apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-reader-role-binding
subjects:
  - kind: User
    name: prod-reader
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-reader-role
  apiGroup: rbac.authorization.k8s.io
